"""add is active to employer

Revision ID: 6e041cf1a497
Revises: d58a14db6abc
Create Date: 2023-12-21 00:53:04.393994

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6e041cf1a497'
down_revision: Union[str, None] = 'd58a14db6abc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employers', sa.Column('is_active', sa.Boolean(), nullable=True))
    op.alter_column('employers', 'email_employer',
               existing_type=sa.VARCHAR(length=30),
               type_=sa.String(length=100),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('employers', 'email_employer',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=30),
               existing_nullable=False)
    op.drop_column('employers', 'is_active')
    # ### end Alembic commands ###
