"""message

Revision ID: 847c20a84fba
Revises: 6e041cf1a497
Create Date: 2023-12-25 14:53:36.652685

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '847c20a84fba'
down_revision: Union[str, None] = '6e041cf1a497'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admins',
    sa.Column('id_admin', sa.Integer(), sa.Identity(always=False, start=1), nullable=False),
    sa.Column('name_admin', sa.String(length=30), nullable=False),
    sa.Column('email_admin', sa.String(length=100), nullable=False),
    sa.Column('password_admin', sa.Text(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('create_at', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('id_admin'),
    sa.UniqueConstraint('email_admin')
    )
    op.create_table('employers',
    sa.Column('id_employer', sa.Integer(), sa.Identity(always=False, start=1), nullable=False),
    sa.Column('identifier_employer', sa.String(length=10), nullable=False),
    sa.Column('name_employer', sa.String(length=30), nullable=False),
    sa.Column('lastname_employer', sa.String(length=30), nullable=False),
    sa.Column('email_employer', sa.String(length=100), nullable=False),
    sa.Column('create_at', sa.Date(), nullable=True),
    sa.Column('face_coding_employer', sa.ARRAY(sa.Double()), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id_employer'),
    sa.UniqueConstraint('email_employer'),
    sa.UniqueConstraint('identifier_employer')
    )
    op.create_table('history',
    sa.Column('id_history', sa.Integer(), sa.Identity(always=False, start=1), nullable=False),
    sa.Column('id_employer', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('date_employer_enter', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['id_employer'], ['employers.id_employer'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id_history')
    )
    op.drop_table('emploiers')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('emploiers',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('lastname', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('numbers', postgresql.ARRAY(sa.INTEGER()), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='emploiers_pkey')
    )
    op.drop_table('history')
    op.drop_table('employers')
    op.drop_table('admins')
    # ### end Alembic commands ###
