"""constraint not null id_employer

Revision ID: 9981111e3a0e
Revises: cc483567c49b
Create Date: 2023-12-16 18:48:52.885155

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9981111e3a0e'
down_revision: Union[str, None] = 'cc483567c49b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('history', 'id_employer',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('history', 'id_employer',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
