"""is active history add

Revision ID: ad33c8526cbf
Revises: 9981111e3a0e
Create Date: 2023-12-16 19:11:20.113305

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ad33c8526cbf'
down_revision: Union[str, None] = '9981111e3a0e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('history', sa.Column('is_active', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('history', 'is_active')
    # ### end Alembic commands ###
