"""create employer

Revision ID: b38da52e6967
Revises: f0a2f555a8cb
Create Date: 2023-12-16 18:33:40.200903

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b38da52e6967'
down_revision: Union[str, None] = 'f0a2f555a8cb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('employers',
    sa.Column('id_employer', sa.Integer(), sa.Identity(always=False, start=1), nullable=False),
    sa.Column('identifier_employer', sa.String(length=10), nullable=False),
    sa.Column('name_employer', sa.String(length=30), nullable=False),
    sa.Column('lastname_employer', sa.String(length=30), nullable=False),
    sa.Column('email_employer', sa.String(length=30), nullable=False),
    sa.Column('create_at', sa.Date(), nullable=True),
    sa.Column('face_coding_employer', sa.ARRAY(sa.Double()), nullable=True),
    sa.PrimaryKeyConstraint('id_employer'),
    sa.UniqueConstraint('email_employer'),
    sa.UniqueConstraint('identifier_employer')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('employers')
    # ### end Alembic commands ###
