"""create history table

Revision ID: cc483567c49b
Revises: b38da52e6967
Create Date: 2023-12-16 18:46:21.947146

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cc483567c49b'
down_revision: Union[str, None] = 'b38da52e6967'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('history',
    sa.Column('id_history', sa.Integer(), sa.Identity(always=False, start=1), nullable=False),
    sa.Column('id_employer', sa.Integer(), nullable=True),
    sa.Column('date_employer_enter', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['id_employer'], ['employers.id_employer'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id_history')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('history')
    # ### end Alembic commands ###
